version: '3.9'

services:
  db:
    image: postgres:16
    container_name: minivehicle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MiniVehicleDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: .                       # die ganze Solution
      dockerfile: ./src/MiniVehicleAPI.Api/Dockerfile
    container_name: minivehicle-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=MiniVehicleDB;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: